language: nix

matrix:
  fast_finish: true
  # subprocess.run was introduced in 3.5
  include:
    - os: linux
      env: PYTHON_VERSION=3.6
      install: travis_wait nix-shell --no-build-output
      script: nix-shell --run "bash scripts/test.sh"

    - os: linux
      env: PYTHON_VERSION=3.5
      install: travis_wait nix-shell --no-build-output
      script: nix-shell --run "bash scripts/test.sh"

    - os: osx
      osx_image: xcode7.3
      before_install:
        - nix-shell -p python36Packages.setuptools -p python36Packages.pip
      install:
        - >
          nix-shell
          -p python36Packages.setuptools -p python36Packages.pip
          --run "pip3 install -r requirements.txt"
        - >
          nix-shell
          -p python36Packages.setuptools -p python36Packages.pip
          --run "python -m nltk.downloader all"
        - >
          nix-shell
          -p python36Packages.setuptools -p python36Packages.pip
          --run "pip3 install -r requirements.txt"
      script:
        - >
          nix-shell
          -p python36Packages.setuptools -p python36Packages.pip
          --run "python3 setup.py test"

  allow_failures:
    - os: linux
      env: PYTHON_VERSION=3.5
