language: nix

matrix:
  fast_finish: true
  # subprocess.run was introduced in 3.5
  include:
    - os: linux
      env: PYTHON_VERSION=3.6
      install: travis_wait nix-shell --no-build-output
      script: nix-shell --run "bash scripts/test.sh"

    - os: linux
      env: PYTHON_VERSION=3.5
      install: travis_wait nix-shell --no-build-output
      script: nix-shell --run "bash scripts/test.sh"

    - os: osx
      osx_image: xcode7.3
      before_install:
        - nix-env -iA nixpkgs.python36Packages.pip
      install:
        - pip install -r requirements.txt
        - python -m nltk.downloader all
      script: ./setup.py test

  allow_failures:
    - os: linux
      env: PYTHON_VERSION=3.5
