language: nix

install:
  - travis_wait nix-shell --no-build-output
  - cd repeat/pdfutil; ./create_pdfs.py; cd -

script: nix-shell --run "bash scripts/test.sh"

env:
  # subprocess.run was introduced in 3.5
  - PYTHON_VERSION=3.5
  - PYTHON_VERSION=3.6

matrix:
  fast_finish: true
  allow_failures:
    - env: PYTHON_VERSION=3.5
